export const GTK_CSS_PROPERTIES = [
    "color",
    "opacity",
    "filter",
    "backdropFilter",
    "backgroundBlendMode",

    "background",
    "backgroundColor",
    "backgroundImage",
    "backgroundPosition",
    "backgroundRepeat",
    "backgroundSize",
    "backgroundClip",
    "backgroundOrigin",

    "border",
    "borderTop",
    "borderRight",
    "borderBottom",
    "borderLeft",
    "borderColor",
    "borderTopColor",
    "borderRightColor",
    "borderBottomColor",
    "borderLeftColor",
    "borderWidth",
    "borderTopWidth",
    "borderRightWidth",
    "borderBottomWidth",
    "borderLeftWidth",
    "borderStyle",
    "borderTopStyle",
    "borderRightStyle",
    "borderBottomStyle",
    "borderLeftStyle",
    "borderSpacing",

    "borderRadius",
    "borderTopLeftRadius",
    "borderTopRightRadius",
    "borderBottomRightRadius",
    "borderBottomLeftRadius",

    "borderImage",
    "borderImageSource",
    "borderImageRepeat",
    "borderImageSlice",
    "borderImageWidth",

    "boxShadow",
    "textShadow",

    "outline",
    "outlineStyle",
    "outlineWidth",
    "outlineColor",
    "outlineOffset",

    "margin",
    "marginTop",
    "marginRight",
    "marginBottom",
    "marginLeft",
    "padding",
    "paddingTop",
    "paddingRight",
    "paddingBottom",
    "paddingLeft",
    "minWidth",
    "minHeight",

    "font",
    "fontFamily",
    "fontSize",
    "fontStyle",
    "fontWeight",
    "fontStretch",
    "fontVariant",
    "fontVariantLigatures",
    "fontVariantPosition",
    "fontVariantCaps",
    "fontVariantNumeric",
    "fontVariantAlternates",
    "fontVariantEastAsian",
    "fontFeatureSettings",
    "fontVariationSettings",
    "fontKerning",

    "lineHeight",
    "letterSpacing",
    "textTransform",
    "textDecoration",
    "textDecorationLine",
    "textDecorationColor",
    "textDecorationStyle",
    "caretColor",

    "transform",
    "transformOrigin",
    "scale",
    "rotate",

    "transition",
    "transitionProperty",
    "transitionDuration",
    "transitionTimingFunction",
    "transitionDelay",
    "animation",
    "animationName",
    "animationDuration",
    "animationTimingFunction",
    "animationIterationCount",
    "animationDirection",
    "animationPlayState",
    "animationDelay",
    "animationFillMode",

    "GtkDpi",
    "GtkIconSource",
    "GtkIconSize",
    "GtkIconStyle",
    "GtkIconTransform",
    "GtkIconPalette",
    "GtkIconFilter",
    "GtkIconShadow",
    "GtkIconWeight",
    "GtkSecondaryCaretColor",

    "pointerEvents",
    "visibility",
] as const;

export type GtkCssProperty = (typeof GTK_CSS_PROPERTIES)[number];
