name: Build CI Image
description: Build CI Docker image with layer caching

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build CI image
      uses: docker/build-push-action@v6
      with:
        context: .github/docker
        load: true
        tags: gtkx-ci:local
        cache-from: type=gha
        cache-to: type=gha,mode=max
